rl_srt:
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.5
    epsilon_discount: 0.999
    nepisodes: 110
    nsteps: 1000
    number_splits: 100
    
    running_step: 0.06
    wait_time: 0.1

    n_actions: 2

    move_time: 0.1

    speed_step: 0.1
    max_speed: 30.0
    min_speed: 20.0
    max_steer: 1.0
    min_steer: -1.0

    end_episode_points: 1000 
